### ISSUE TITLE
webpack环境启动后出现大量 Prettier 格式错误

### ISSUE THREAD

**Issue by LetTTGACO** [zh-lx/code-inspector#105]
不太清楚什么原理，去掉插件项目就正常启动了，安装上就会报项目源文件 Prettier 格式错误。

<img width="1425" alt="image" src="https://github.com/zh-lx/code-inspector/assets/37357188/9baa5698-0391-4f86-a41e-7f13daf65ce1">

**Comment by zh-lx** [comment]
插件参数设置 `enforcePre: false` 试试

**Comment by LetTTGACO** [comment]
webstorm窗口跳出来了 但是是个空白窗口 啥都没有，希望可以支持下

**Comment by zh-lx** [comment]
> webstorm窗口跳出来了 但是是个空白窗口 啥都没有，希望可以支持下

webstorm 的版本是多少？

**Comment by LetTTGACO** [comment]
WebStorm 2023.3.3

**Comment by zh-lx** [comment]
方便加群或者微信看下具体现象不

**Comment by LetTTGACO** [comment]
好的 我整理下问题 发到群里
