### ISSUE TITLE
IntelliJ IDEA  The editor process exited with an error: spawn code ENOENT.

### ISSUE THREAD

**Issue by laokaikai** [zh-lx/code-inspector#110]
![image](https://github.com/zh-lx/code-inspector/assets/13110705/c25776b4-1763-451b-8793-26db887dfb7d)
![image](https://github.com/zh-lx/code-inspector/assets/13110705/f0476419-e7d1-4d70-a584-be85e9f754f8)
![image](https://github.com/zh-lx/code-inspector/assets/13110705/703f576d-20e1-41df-b08a-96f62479ec2d)

nodejs version: v14.14.0
npm: 6.14.8

**Comment by zh-lx** [comment]
不是设置 code，参考 https://inspector.fe-dev.cn/guide/ide.html#%E5%85%B6%E4%BB%96-ide 设置
