### ISSUE TITLE
Vue3 如果注册全局的 warnHandler 拦截，会报 data-insp-path 的注入 warn

### ISSUE THREAD

**Issue by wuhaohuang** [zh-lx/code-inspector#116]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息
```
// 全局 warn
app.config.warnHandler = (err, vm, info) => {
  console.log('[全局warn]', err, vm, info);
};
```
Extraneous non-props attributes (data-insp-path) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 

![image](https://github.com/zh-lx/code-inspector/assets/19322584/8a6a31dd-b196-4e65-b315-68cac2caaf30)

有没有什么办法可以不报

**Comment by zh-lx** [comment]
收到，我优化一下

**Comment by wuhaohuang** [comment]
还会报一个未知错误：Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core . 

![image](https://github.com/zh-lx/code-inspector/assets/19322584/69b503f3-6c19-4b5a-8cd9-306d698c1d5e)

一用就会报，不用就不报

**Comment by zh-lx** [comment]
> @zh-lx 还会报一个未知错误：Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core .
> 
> ![image](https://private-user-images.githubusercontent.com/19322584/302566599-69b503f3-6c19-4b5a-8cd9-306d698c1d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTMzODAsIm5iZiI6MTcwNzIxMzA4MCwicGF0aCI6Ii8xOTMyMjU4NC8zMDI1NjY1OTktNjliNTAzZjMtNmMxOS00YjVhLThjZDktMzA2ZDY5OGMxZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA5NTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YzUyMmRhZTY0ZmRjOGI4Y2M0NTJkYjhkZTg4NjhhZmQ2MTBjY2Y2YjBlYWRjODU1YTRlMWIyNWM3MGJmZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2vot8IbescOGH3zolHwSMBrvIxVxT_GrC4R7F1cP1sw)
> 
> 一用就会报，不用就不报

方便提供一个复现仓库吗，这种问题无复现仓库没法排查

**Comment by zh-lx** [comment]
已在 `0.8.0`  版本中修复了 warning 的问题，未知错误辛苦提供个可复现仓库

**Comment by zh-lx** [comment]
> > 已在 `0.8.0` 版本中修复了 warning 的问题，未知错误辛苦提供个可复现仓库
> 
> ![image](https://private-user-images.githubusercontent.com/88535245/323511189-5ea65e52-159c-4bd7-bf02-4b4d346119d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjY1NjcsIm5iZiI6MTcxMzQyNjI2NywicGF0aCI6Ii84ODUzNTI0NS8zMjM1MTExODktNWVhNjVlNTItMTU5Yy00YmQ3LWJmMDItNGI0ZDM0NjExOWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNjQzOTQxN2UzZmVkNzRhYTkyMDQ4NWExNjJmODRiYzc2MWNkYjM4ZWNmN2I3ZGYxNTBmODYzMTJhNmZlNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ECrnr9qCF-wT7FKCJTvAOxSThUpsYcQ2PS_NOV42N3s)
> 
> 在0.11.0版本中 vconsole还是有类似警告

方便提供一个可复现的仓库看下不
