### ISSUE TITLE
[BUG]Pycharm和Webstorm同时使用时, 错误地在pycharm中打开文件

### ISSUE THREAD

**Issue by TonyYanOnFire** [zh-lx/code-inspector#119]
## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [ ] 点击筛选框无法打开 IDE
- [x] 其他问题

## Bug 描述

1. 先打开pycharm
2. 再打开webstorm并运行前端项目
3. 在页面中点击元素尝试打开相应文件, 会发现文件在pycharm而不是webstorm中打开

## 你使用的打包器及版本

- [x] webpack
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [ ] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] solid
- [ ] preact
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by TonyYanOnFire** [comment]
我猜测是在选择具体的IDE时如果存在多个合法的IDE, 优先级是进程在前的(最早打开的). 如果是的话, 能够考虑赋予webstorm比pycharm的更高的优先级?

**Comment by zh-lx** [comment]
这个是看系统进程中项目排序，一般来说可能按照 IDE 的字母来的，可以在 `.env.local` 中指定要打开的 IDE，参照：https://inspector.fe-dev.cn/guide/ide.html

**Comment by TonyYanOnFire** [comment]
> 这个是看系统中的进程排序，一般来说可能按照 IDE 的字母来的，可以在 `.env.local` 中指定要打开的 IDE，参照：https://inspector.fe-dev.cn/guide/ide.html

我尝试了指定为webstorm, 但在我描述的这个情况还是会在pycharm中打开

**Comment by zh-lx** [comment]
> > 这个是看系统中的进程排序，一般来说可能按照 IDE 的字母来的，可以在 `.env.local` 中指定要打开的 IDE，参照：https://inspector.fe-dev.cn/guide/ide.html
> 
> 我尝试了指定为webstorm, 但在我描述的这个情况还是会在pycharm中打开

是 windows 还是 mac 系统？

**Comment by TonyYanOnFire** [comment]
> > > 这个是看系统中的进程排序，一般来说可能按照 IDE 的字母来的，可以在 `.env.local` 中指定要打开的 IDE，参照：https://inspector.fe-dev.cn/guide/ide.html
> > 
> > 
> > 我尝试了指定为webstorm, 但在我描述的这个情况还是会在pycharm中打开
> 
> 是 windows 还是 mac 系统？

windows. 另外我尝试了指定为vscode, 并且在没有启动vscode的情况下点击元素, 是可以成功唤醒vscode并打开文件的

**Comment by zh-lx** [comment]
> > > > 这个是看系统中的进程排序，一般来说可能按照 IDE 的字母来的，可以在 `.env.local` 中指定要打开的 IDE，参照：https://inspector.fe-dev.cn/guide/ide.html
> > > 
> > > 
> > > 我尝试了指定为webstorm, 但在我描述的这个情况还是会在pycharm中打开
> > 
> > 
> > 是 windows 还是 mac 系统？
> 
> windows. 另外我尝试了指定为vscode, 并且在没有启动vscode的情况下点击元素, 是可以成功唤醒vscode并打开文件的

那可能是 webstorm 的版本和默认识别的有差异，可以参照手动设置 webstorm 的执行路径解决：https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F

**Comment by TonyYanOnFire** [comment]
> > > > > 这个是看系统中的进程排序，一般来说可能按照 IDE 的字母来的，可以在 `.env.local` 中指定要打开的 IDE，参照：https://inspector.fe-dev.cn/guide/ide.html
> > > > 
> > > > 
> > > > 我尝试了指定为webstorm, 但在我描述的这个情况还是会在pycharm中打开
> > > 
> > > 
> > > 是 windows 还是 mac 系统？
> > 
> > 
> > windows. 另外我尝试了指定为vscode, 并且在没有启动vscode的情况下点击元素, 是可以成功唤醒vscode并打开文件的
> 
> 那可能是 webstorm 的版本和默认识别的有差异，可以参照手动设置 webstorm 的执行路径解决：https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F

可以了
