### ISSUE TITLE
打开ide失败

### ISSUE THREAD

**Issue by mayflower-zc** [zh-lx/code-inspector#120]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [x] 点击筛选框无法打开 IDE
- [ ] 其他问题

## Bug 描述

先打开IntelliJ IDEA， 再打开vs code， 代码指定的是code，结果打开的ide是IntelliJ IDEA。期望打开vs code。
控制台出现异常如下：
<img width="1474" alt="截图" src="https://github.com/zh-lx/code-inspector/assets/6245772/69d61fe1-c86e-4cbe-b56c-934874807d0e">

## 你使用的打包器及版本

- [x] webpack
- [x] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [x] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] solid
- [ ] preact
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
系统是windows还是mac？是否使用了 wsl 或者虚拟机等？

**Comment by mayflower-zc** [comment]
win11

**Comment by mayflower-zc** [comment]
<img width="809" alt="截图" src="https://github.com/zh-lx/code-inspector/assets/6245772/4d254429-5b02-4dd3-b1d5-ba28ae4daf7b">
这个customEditors 返回的结果是['code'] 与processName Code.exe 不匹配，期望是match的。
修改一下代码成功：
![Uploading 截图2.PNG…]()

**Comment by zh-lx** [comment]
已在 `0.8.1-beta.1` 版本中修复了该问题，可以安装体验一下
