### ISSUE TITLE
代码里加了 debugger 后，chrome 跳转的 源代码位置不对

### ISSUE THREAD

**Issue by jo0ger** [zh-lx/code-inspector#123]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [ ] 点击筛选框无法打开 IDE
- [x] 其他问题

## Bug 描述

![image](https://github.com/zh-lx/code-inspector/assets/16385416/46e5b40f-c36b-4238-b303-b0b7c7586b35)

## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [x] mac
- [ ] linux

## 你使用的打包器及版本

- [x] webpack5
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [x] react
- [ ] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] solid
- [ ] preact
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
已在 `0.8.1-beta.3` 中修复
