### ISSUE TITLE
可以提供控制台 提示 的关闭配置吗，不然控制台输出信息太杂乱了

### ISSUE THREAD

**Issue by cjh-store** [zh-lx/code-inspector#131]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

_请描述一下你的功能……_
可以提供控制台 提示 的关闭配置吗，不然控制台输出信息太杂乱了

**Comment by zh-lx** [comment]
可以添加 `hideConsole: true` 配置关闭提示，参照 [hideConsole](https://inspector.fe-dev.cn/guide/api.html#hideconsole)
