### ISSUE TITLE
php + twig 失效

### ISSUE THREAD

**Issue by FengHaiSheng** [zh-lx/code-inspector#132]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## Bug 类型

- [ ] 按住组合键无筛选框

## Bug 描述

我们的项目是在php的Symfony + twig之下开发的，只针对.js、.vue、.less和资源进行了webpack的编译打包，twig上在利用nginx代理到webpack启动的服务之下访问 index.js，index.js 内去 new Vue。

[Tips] 也是在这个项目之内，我用webpack5 + Vue3 +  Ant-Design-Vue@4 使用的是正常的

![image](https://github.com/zh-lx/code-inspector/assets/14888544/245fa717-dee8-4e3d-af73-f23d73e602d1)

## 系统

- [ ] mac

## 你使用的打包器及版本

- [ ] webpack@4

## 你使用的 web 框架

- [ ] vue@2

## 自检信息

- 浏览器、IDE、代码在一台机器上
- 浏览器控制台没有打印组合按键提示信息
- 页面 DOM 有注入 `data-insp-path` 属性了

**Comment by zh-lx** [comment]
这个项目最终的渲染方式是服务端渲染还是客户端渲染？

**Comment by FengHaiSheng** [comment]
> 这个项目最终的渲染方式是服务端渲染还是客户端渲染？

客户端渲染

**Comment by zh-lx** [comment]
> > 这个项目最终的渲染方式是服务端渲染还是客户端渲染？
> 
> 客户端渲染

目前无复现环境没法排查，看起来像是服务端渲染导致 window 对象为空，因此交互逻辑代码注入失败

**Comment by FengHaiSheng** [comment]
好的。等我这次的项目发布了，我再来弄一个简单的安装复现环境的文档

**Comment by zh-lx** [comment]
看看没啥其他问题的话我暂时先关闭了，还有问题的话可以加群我进一步跟进
