### ISSUE TITLE
hotKeys 配置

### ISSUE THREAD

**Issue by txs00** [zh-lx/code-inspector#140]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息
## 插件版本
_请提供使用的 code-inspector-plugin 版本号……_

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [ ] 点击筛选框无法打开 IDE
- [] 其他问题

## Bug 描述
可以正常使用 但是hotKeys 组合配置项不生效

## 系统

- [] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [ ] mac
- [ ] linux

## 你使用的打包器及版本

- [ ] webpack
- [] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] 其他

## 自检信息

- [ ] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [ ] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [ ] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by txs00** [comment]
版本 "code-inspector-plugin": "^0.9.3",
demo案例中测试发现也是无效的

**Comment by zh-lx** [comment]
配置的组合键是什么的？

**Comment by txs00** [comment]
单独的 ctrl  和 ctrl+alt

**Comment by zh-lx** [comment]
感谢反馈，已在 `0.10.0` 版本中修复了该问题，请安装最新版本体验一下
