### ISSUE TITLE
F12控制台 给元素添加的自定义属性 data-insp-path  添加的路径 能不能转换简写一下

### ISSUE THREAD

**Issue by hulovexu1314** [zh-lx/code-inspector#142]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

F12控制台 给元素添加的自定义属性 data-insp-path  的路径能简写吗？

**Comment by zh-lx** [comment]
你指的是这个属性的名称还是属性的路径值写成相对路径？属性名称我回头可以增加一个自定义名称配置，值的话使用相对路径在微前端项目中会有问题，所以目前采取绝对路径

**Comment by hulovexu1314** [comment]
> 你指的是这个属性的名称还是属性的路径值写成相对路径？属性名称我回头可以增加一个自定义名称配置，值的话使用相对路径在微前端项目中会有问题，所以目前采取绝对路径
或者 F12控制台 直接不显示 data-insp-path 这个属性。太长了F12审查元素时，路径长看得眼睛痛。。。我知道可能不好实现。。。。。。

**Comment by zh-lx** [comment]
> > 你指的是这个属性的名称还是属性的路径值写成相对路径？属性名称我回头可以增加一个自定义名称配置，值的话使用相对路径在微前端项目中会有问题，所以目前采取绝对路径
> 
> 或者 F12控制台 直接不显示 data-insp-path 这个属性。太长了F12审查元素时，路径长看得眼睛痛。。。我知道可能不好实现。。。。。。

改控制台我们是无能为力的🤦🏻‍♀️

**Comment by zh-lx** [comment]
已在 `0.12.0` 版本中支持，添加 `hideDomPathAttr: true` 配置即可：https://inspector.fe-dev.cn/en/guide/api.html#hidedompathattr
