### ISSUE TITLE
跳转路由对应界面

### ISSUE THREAD

**Issue by ljw-codeking** [zh-lx/code-inspector#143]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

希望加个按钮通过地址栏URL跳转到项目中对应路由文件

为什么？

因为项目中页面元素大多都抽象成了组件，有时候跳转到组件文件会需要一直往上查找到对应路由文件。

**Comment by zh-lx** [comment]
这个功能和目前插件的逻辑实现上没有关联性，因此不考虑在此插件中实现该功能
