### ISSUE TITLE
支持 VSCode remote

### ISSUE THREAD

**Issue by cuishuo0102** [zh-lx/code-inspector#144]
## 功能描述

现有版本在 VSCode remote 项目上使用，点击页面元素会打开远程主机的编辑器，例如在我的 VSCode 里是在命令行打开远程机器的 Vim 编辑器

希望现有版本早日在 VSCode  remote 上也可以使用

**Comment by zh-lx** [comment]
vscode remote 是用的 wsl 的吗？

**Comment by cuishuo0102** [comment]
> vscode remote 是用的 wsl 的吗？

VS Code devContainer -> Docker Desktop -> WSL2

**Comment by zh-lx** [comment]
> > vscode remote 是用的 wsl 的吗？
> 
> VS Code devContainer -> Docker Desktop -> WSL2

可以参照 [其他IDE](https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F) 一节找到 windows vscode 的可执行路径，将可执行路径中的硬盘符替换为 `/mnt/盘符`，例如设置 `.env.local` 如下：
```perl
# .env.local
# 可执行路径为 D:/Users/abc/AppData/Local/Programs/Microsoft VS Code/Code.exe 则替换 D: 为 /mnt/d
CODE_EDITOR=CODE_EDITOR=/mnt/d/Users/abc/AppData/Local/Programs/Microsoft VS Code/Code.exe
```

**Comment by zcqno1** [comment]
> > > vscode remote 是用的 wsl 的吗？
> > 
> > 
> > VS Code devContainer -> Docker Desktop -> WSL2
> 
> 可以参照 [其他IDE](https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F) 一节找到 windows vscode 的可执行路径，将可执行路径中的硬盘符替换为 `/mnt/盘符`，例如设置 `.env.local` 如下：
> 
> ```perl
> # .env.local
> # 可执行路径为 D:/Users/abc/AppData/Local/Programs/Microsoft VS Code/Code.exe 则替换 D: 为 /mnt/d
> CODE_EDITOR=CODE_EDITOR=/mnt/d/Users/abc/AppData/Local/Programs/Microsoft VS Code/Code.exe
> ```

使用作者的方法后，我的项目实际独立打开了一个vscode，可以通过在wsl中使用`which code`找到vscode remote的地址，地址差不多长这样
```shell
/home/xxx/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/remote-cli/code
```
