### ISSUE TITLE
next 13.5.6 插件会偶尔失效

### ISSUE THREAD

**Issue by kingkong0828** [zh-lx/code-inspector#147]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息
## 插件版本
_请提供使用的 code-inspector-plugin 版本号……_0.10.0

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [x] 按住组合键无筛选框
- [ ] 点击筛选框无法打开 IDE
- [ ] 其他问题

## Bug 描述

next12.5.6 会大概率出现按住组合键无筛选框问题

## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [x] mac
- [ ] linux

## 你使用的打包器及版本

- [x] webpack
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [ ] vue
- [ ] nuxt
- [x] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [ ] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
目前插件的交互逻辑是自动寻找第一个 `.js/.ts` 文件注入逻辑，在 nextjs 中，会注入到第一个含有 `use client` 的客户端组件文件中(插件的交互逻辑在 ssr 场景中只能在同构或者纯客户端文件中生效)。你可以使用 `injectTo` 指定一个所有页面共用的客户端文件以保证每个页面都能生效，参考 [injectTo](https://inspector.fe-dev.cn/guide/api.html#injectto)
