### ISSUE TITLE
能不能把 escapeTags 也加在参数中呢？

### ISSUE THREAD

**Issue by Mercizzy** [zh-lx/code-inspector#148]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

_请描述一下你的功能……_
您好，我的项目是 Next.js ，UI 框架是 mui，mui 中有一些 tag，比如 themeProvider 等等是不需要加上 data-insp-path 参数的，加上了之后，页面会一直有警告：_app.tsx:55 Warning: Failed prop type: The following props are not supported: `data-insp-path`. Please remove them.
刚刚看了您的代码，在向 dom 元素添加 data-insp-path 参数前，排除了 escapeTags 数组中的 dom 元素，但是 escapeTags 是写死在项目中的，希望能够变成可配置的，谢谢！

**Comment by zh-lx** [comment]
感谢反馈，在 `0.11.0` 版本中支持了该功能，欢迎安装体验。详细参考 [escapetags](https://inspector.fe-dev.cn/guide/api.html#escapetags)
