### ISSUE TITLE
Windows下next项目的文件有些情况打不开

### ISSUE THREAD

**Issue by JR-Chen-1998** [zh-lx/code-inspector#150]
![QQ截图20240410151127](https://github.com/zh-lx/code-inspector/assets/50216424/4545bab3-39db-4ccd-9526-826129809bd8)

我的next项目做了动态路由，如上述文件【banner.tsx】，具体路径为【/app/[lang]/banner.tsx】，类似这种文件路径中包含中括号的，都打不开，上图报错信息说，文件名只能是字母、数字、句号、短划线、斜线、下划线，这样的话就不包括next这种动态路由的中括号了

**Comment by zh-lx** [comment]
感谢反馈，已在 `0.12.0` 版本中修复
