### ISSUE TITLE
uniapp编译成支付宝报错globalThis is not defined

### ISSUE THREAD

**Issue by MuYi086** [zh-lx/code-inspector#164]
## 插件版本
v0.13.0

## Bug 描述
使用uniapp cli 安装最新的模版，初始项目第一次编译成功，引入code-inspector-plugin后，再次编译报错

![1715323624597](https://github.com/zh-lx/code-inspector/assets/18638822/236cd5c2-1762-4037-bae5-1af87c83d630)

## 系统

windows11(未使用 wsl 虚拟机)

## 你使用的打包器及版本
webpack

## 你使用的 web 框架
uniapp + vue
"node-polyfill-webpack-plugin": "^2.0.1",
"@dcloudio/webpack-uni-mp-loader": "2.0.2-4010520240507001",
 "@dcloudio/webpack-uni-pages-loader": "2.0.2-4010520240507001",
"@dcloudio/uni-mp-alipay": "2.0.2-4010520240507001",
"@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-service": "~5.0.0",

uni-app 2.0.2-4010520240507001
vue >= 2.6.14 < 2.7

**Comment by zh-lx** [comment]
感谢反馈，目前不支持在小程序中使用
