### ISSUE TITLE
vite多页面模式下，只有index页面可用插件，其他页面不可以,

### ISSUE THREAD

**Issue by eatfishs** [zh-lx/code-inspector#165]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

_请描述一下你的功能……_
希望能和 vite-plugin-vue-inspector一样支持多页面

**Comment by zh-lx** [comment]
请问方便提供一个可测试仓库看下吗

**Comment by zh-lx** [comment]
已在 `0.17.4` 及以上版本中解决了该问题
