### ISSUE TITLE
新版本的vscode 无法使用

### ISSUE THREAD

**Issue by wubuleiMaikai** [zh-lx/code-inspector#167]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本

0.14.0

## 编辑器版本
vscode : 1.89.1 (Universal)

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [x] 点击筛选框无法打开 IDE
- [ ] 其他问题

## Bug 描述

_请描述一下你的 bug，最好附上一张报错截图……_

1. 我的code命令是正常的。
2. 已经出现了筛选框，但是无法打开IDE，
![image](https://github.com/zh-lx/code-inspector/assets/143771685/75178aba-95dc-43fa-96c6-f616c0f1db81)

## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [x] mac
- [ ] linux

## 你使用的打包器及版本

- [ ] webpack
- [x] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [x] react
- [ ] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
参考这里手动指定一下 IDE 试试：https://inspector.fe-dev.cn/guide/ide.html#%E6%8C%87%E5%AE%9A-ide

**Comment by wubuleiMaikai** [comment]
> 参考这里手动指定一下IDE试试：https://inspector.fe-dev.cn/guide/ide.html#%E6%8C%87%E5%AE%9A-ide

之前已经尝试过指定了，还是不生效，升级vscode版本之前还是正常的，升级后今天就不正常了😂

![image](https://github.com/zh-lx/code-inspector/assets/143771685/b7295972-b897-49d8-bc2f-34dff5b066a3)
![image](https://github.com/zh-lx/code-inspector/assets/143771685/53ec029c-b53d-4160-8b02-c98b630e734f)

**Comment by zh-lx** [comment]
可能是新版 vscode 路径之类的换了，可以先参考 https://inspector.fe-dev.cn/guide/ide.html#mac-%E7%B3%BB%E7%BB%9F 这个教程，指定下 vscode 路径。然后新版待会儿我升级看看

**Comment by wubuleiMaikai** [comment]
> 可能是新版 vscode 路径之类的换了，可以先参考 https://inspector.fe-dev.cn/guide/ide.html#mac-%E7%B3%BB%E7%BB%9F 这个教程，指定下 vscode 路径。然后新版待会儿我升级看看

按照这个步骤，使用生效了，感谢

**Comment by zh-lx** [comment]
升级到了新版本，暂未发现该问题，先暂时关闭了，后续如有其他用户反馈相同问题再归类~
