### ISSUE TITLE
vscode 偶尔跳转会打开， 大部分时候都是要手动切换窗口

### ISSUE THREAD

**Issue by eachann1024** [zh-lx/code-inspector#168]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本

"code-inspector-plugin": "^0.13.0",

## Bug 类型

- [ x ] 点击筛选框无法打开 IDE

## Bug 描述

没有报错

## 系统
- win 11

- [ ] webpack
- [ x ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [ x ] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [ ] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [ x ] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [ x ] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
感谢反馈，这个是 windows 系统的进程调度问题，无法从插件层面解决，因此不属于一个 bug~

**Comment by eachann1024** [comment]
> 感谢反馈，这个是 windows 系统的进程调度问题，无法从插件层面解决，因此不属于一个 bug~

哈哈 了解了
