### ISSUE TITLE
cros错误

### ISSUE THREAD

**Issue by kikyouink** [zh-lx/code-inspector#170]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本

_请提供使用的 code-inspector-plugin 版本号……_
0.10.0

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [✅] 点击筛选框无法打开 IDE
- [ ] 其他问题

## Bug 描述

_请描述一下你的 bug，最好附上一张报错截图……_
在点击打开IDE时遇到了CROS错误，因为我本地的地址`https://localhost:8080`，通过改`host`映射为了`https://test.local.com:8080`，报错`has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space local`.

## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [✅] mac
- [ ] linux

## 你使用的打包器及版本

- [✅] webpack3
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [✅] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [✅] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [✅] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [✅] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
这个是 chrome 浏览器安全策略引起的，可以通过如下方式解决：
访问 `chrome://flags/`，搜索找到 `Block insecure private network requests` 这一项，设置为 `disabled` 即可正常使用。
<img width="1520" alt="image" src="https://github.com/zh-lx/code-inspector/assets/73059627/7b50c7e2-01d6-490a-9263-94ca83c9029a">

**Comment by kikyouink** [comment]
> 这个是 chrome 浏览器安全策略引起的，可以通过如下方式解决： 访问 `chrome://flags/`，搜索找到 `Block insecure private network requests` 这一项，设置为 `disabled` 即可正常使用。
> 
> <img alt="image" width="1520" src="https://private-user-images.githubusercontent.com/73059627/335146177-7b50c7e2-01d6-490a-9263-94ca83c9029a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjU3MzcsIm5iZiI6MTcxNzA2NTQzNywicGF0aCI6Ii83MzA1OTYyNy8zMzUxNDYxNzctN2I1MGM3ZTItMDFkNi00OTBhLTkyNjMtOTRjYTgzYzkwMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEwMzcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZTMyZTUyYjk4Yzg0MjU3YmVkNzdiZmYwNzlhMDQ2NmFmMDJjZWRjMDVhMzYzMjdiYTM5MmQyNmQzYzE2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gEjvmzByabKvpKKq3ozHIsHkj8tvikJnScMWWp_Dwhs">

谢谢
