### ISSUE TITLE
遍历JSXElement节点的时候，没有区分是react组件还是普通html标签，导致给react组件添加一个data-insp-path属性

### ISSUE THREAD

**Issue by senfish** [zh-lx/code-inspector#171]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本
version: ^0.14.0

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [ ] 点击筛选框无法打开 IDE
- [x] 其他问题

## Bug 描述
app.jsx
<img width="592" alt="image" src="https://github.com/zh-lx/code-inspector/assets/49187663/781e7b19-266d-473f-b0ed-cf2f3f358d41">
user.jsx
<img width="554" alt="image" src="https://github.com/zh-lx/code-inspector/assets/49187663/fabca462-e4be-4ac5-91a7-a873c2523c3c">
浏览器控制台
<img width="691" alt="image" src="https://github.com/zh-lx/code-inspector/assets/49187663/93d4dc2d-c891-4fe0-a05a-af5e414b9218">

[源码地址](https://github.com/zh-lx/code-inspector/blob/main/packages/core/src/server/transform/transform-jsx.ts#L33)
## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [x] mac
- [ ] linux

## 你使用的打包器及版本

- [x] webpack
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [x] react
- [ ] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [ ] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [ ] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [ ] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
这个是插件特意如此设置的，因为对于第三方组件库，无法参与组件内部源码的编译，所以必须给组件节点上注入属性(react 默认会继承到组件根节点)。

如果对你的业务有影响，可以将插件的 [escapeTags](https://inspector.fe-dev.cn/guide/api.html#escapetags) 属性设置为 `/^[A-Z].*/` 排除掉组件注入(视大写字母开头的为组件)

**Comment by senfish** [comment]
感谢回复，昨天想了一下，除了你说的这种方法，感觉好像比较难区分到底是react业务组件还是antd的Button组件

**Comment by zh-lx** [comment]
> 感谢回复，昨天想了一下，除了你说的这种方法，感觉好像比较难区分到底是react业务组件还是antd的Button组件

嗯，如果想要排除业务组件而又不排除 antd 的组件确实比较麻烦，只能写个正则保留你需要常用的 antd 组件如 `Button`、`Select`、`Input` 等，例如：`^(?!Button|Input|Select)[A-Z][a-zA-Z]*`
