### ISSUE TITLE
支持angular

### ISSUE THREAD

**Issue by K332** [zh-lx/code-inspector#172]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

支持angular框架

**Comment by zh-lx** [comment]
会考虑，不过可能要放在一个月后

**Comment by K332** [comment]
为什么 npm run serve-prod还是能跳转呀，控制台也有显示，vue-cli项目

**Comment by zh-lx** [comment]
> 为什么 npm run serve-prod还是能跳转呀，控制台也有显示，vue-cli项目

目前的环境判断逻辑是 `webpack.compiler.mode` 和 `process.env.NODE_ENV` 其中有一个为 `development` 即判断为开发环境。应该是你们 `serve` 模式下的 `webpack.compiler.mode` 是 `development`。

你可以通过插件的 `dev` 参数配置写一个函数去指定判断当前的环境，参考：[dev](https://inspector.fe-dev.cn/guide/api.html#dev)

**Comment by K332** [comment]
> > 为什么 npm run serve-prod还是能跳转呀，控制台也有显示，vue-cli项目
> 
> 目前的环境判断逻辑是 `webpack.compiler.mode` 和 `process.env.NODE_ENV` 其中有一个为 `development` 即判断为开发环境。应该是你们 `serve` 模式下的 `webpack.compiler.mode` 是 `development`。
> 
> 要解决这个问题，你可以通过插件的 `dev` 参数配置写一个函数去指定判断当前的环境，参考：[dev](https://inspector.fe-dev.cn/guide/api.html#dev)

谢谢，解决了，不过装了这个插件感觉打包速度好像变慢了
