### ISSUE TITLE
antd 弹窗无法定位

### ISSUE THREAD

**Issue by qfkobe24** [zh-lx/code-inspector#186]
> 提示：使用antd + umi 引入插件都可以正常跳转vscode，但ant modal无法被定位

## 插件版本

code-inspector-core-0.14.2

## Bug 类型

- [x] 其他问题

## Bug 描述
umi.config.js
**export default defineConfig({
  publicPath: historyType === 'hash' ? './' : '/',
  devtool: 'eval-cheap-module-source-map',
  chainWebpack(memo) {
    memo.plugin('code-inspector-plugin').use(
      codeInspectorPlugin({
        bundler: 'webpack',
        hideDomPathAttr: true,
      })
    );
  },
});
**

![image](https://github.com/user-attachments/assets/24b98ed5-f84f-4b6b-a013-7d5afaade1b7)

## 系统

- [x] mac
## 你使用的打包器及版本

- [ x] umijs

## 你使用的 web 框架

- [x] react

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
仅支持 jsx 语法的弹窗，你的 modal 是写在 jsx 中的还是静态方法调用的？

**Comment by tianyingchun** [comment]
文件路径的准确性, 可以参考 babel-react-preset 对 source 组件级别的定位. 

https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-react-jsx/src/create-plugin.ts

就更完美了.

**Comment by tianyingchun** [comment]
比如 import { Image } from 'antd'

<Image src="" / > 这个时候 image 无法定位. https://react-dev-inspector.zthxxx.me/docs/compiler-plugin  这个插件可以,

除了此问题, 此插件模式很不错.

**Comment by zh-lx** [comment]
> 文件路径的准确性, 可以参考 babel-react-preset 对 source 组件级别的定位.
> 
> https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-react-jsx/src/create-plugin.ts
> 
> 就更完美了.

这个是专门给 react 官方做 jsx 转换的，会将 jsx 转换成 js，而我们的插件只能做 jsx 增强，不能去转换成 js，不然会影响用户原有的打包逻辑

**Comment by zh-lx** [comment]
> 比如 import { Image } from 'antd'
> 
> <Image src="" / > 这个时候 image 无法定位. https://react-dev-inspector.zthxxx.me/docs/compiler-plugin 这个插件可以,
> 
> 除了此问题, 此插件模式很不错.

这个我看一下

**Comment by tianyingchun** [comment]
此外: `data-insp-path` 在 next.js , html级别 不能 隐藏.
<img width="896" alt="image" src="https://github.com/user-attachments/assets/924b4617-569b-490a-9ab7-cc0da39ada17">
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/b4179708-a4f9-4e15-81f0-9b0d7188fca7">

**Comment by zh-lx** [comment]
> 此外: `data-insp-path` 在 next.js , html级别 不能 隐藏. <img alt="image" width="896" src="https://private-user-images.githubusercontent.com/2833251/351252088-924b4617-569b-490a-9ab7-cc0da39ada17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQzNDksIm5iZiI6MTcyMTczNDA0OSwicGF0aCI6Ii8yODMzMjUxLzM1MTI1MjA4OC05MjRiNDYxNy01NjliLTQ5MGEtOWFiNy1jYzBkYTM5YWRhMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTEyNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ4N2Q3ZmZmODllMDJkMzJmY2FiY2Y0MjNhYjM4NDdhNjkzODk5ZjU5MjRjNzg5MzRjY2JjZWMzYzVlZTlkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VfUl6pcOcK1m6dlx8fp5-LOQQJlTZR2wut0oTPYEgFA"> <img alt="image" width="1027" src="https://private-user-images.githubusercontent.com/2833251/351252430-b4179708-a4f9-4e15-81f0-9b0d7188fca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQzNDksIm5iZiI6MTcyMTczNDA0OSwicGF0aCI6Ii8yODMzMjUxLzM1MTI1MjQzMC1iNDE3OTcwOC1hNGY5LTRlMTUtODFmMC05YjBkNzE4OGZjYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTEyNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk5YTk2NDAzY2RlNGEyMTMxNzQ3MWMwZDAyYmY2NmFlMTg3OTY0NTRhZDI1YTU5NzU2ZjY3NWQwMDZkMjc5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-3H6m-OZQlYVgLdDNj83FZZysteCAX4IMynLxCX1ACE">

跟级别无关，SSR 模式下暂时就不要设置 `hideDomPathAttr: true` 了，插件暂时无法兼顾 SSR 场景下的这个问题
