### ISSUE TITLE
有计划支持 Esbuild 吗？

### ISSUE THREAD

**Issue by sanyuan0704** [zh-lx/code-inspector#187]
## 功能描述

最近在使用 esbuild 打包项目的过程中遇到了类似的需求，请问这个项目有计划支持 esbuild 吗？兼容 esbuild 的成本如何？

**Comment by zh-lx** [comment]
感谢大佬反馈，我评估一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月19日 21:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [zh-lx/code-inspector] 有计划支持 Esbuild 吗？ (Issue #187) |

功能描述

最近在使用 esbuild 打包项目的过程中遇到了类似的需求，请问这个项目有计划支持 esbuild 吗？兼容 esbuild 的成本如何？

**Comment by zh-lx** [comment]
在 `0.15.0` 版本中支持了 esbuild，配置如下：

需要注意的是，esbuild 中使用时，dev 函数的返回值需自己根据环境判断，本地开发的环境返回 true，线上打包返回 false。如果开发环境和生产环境使用两套配置的话，直接设置 `dev: true` 就可以

```js
const esbuild = require('esbuild');
const { codeInspectorPlugin } = require('code-inspector-plugin');

const isDev = process.env.NODE_ENV === 'development'; // 根据自己的配置去设置 isDev 的值

esbuild.build({
  // other configs...

  plugins: [codeInspectorPlugin({ bundler: 'esbuild', dev: () => isDev })],
});
```
