### ISSUE TITLE
mac 每次跳转 vscode 都会打开一个新的图标

### ISSUE THREAD

**Issue by angelbeatsying** [zh-lx/code-inspector#196]
<img width="471" alt="image" src="https://github.com/user-attachments/assets/b5ce93e7-6f1c-430b-a677-81fc027b6609">

配置：   
 config.plugins.push(codeInspectorPlugin({ bundler: 'webpack', hideDomPathAttr: true, openIn: 'reuse' }));

**Comment by angelbeatsying** [comment]
这个是需要在 vscode 中配置吗

**Comment by zh-lx** [comment]
这是 mac 上 vs 进程唤起的正常现象，除了唤起时的瞬间多个图标应该没任何影响吧？
