### ISSUE TITLE
错误打开新的Webstorm

### ISSUE THREAD

**Issue by Super-LUOKI** [zh-lx/code-inspector#201]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本

"code-inspector-plugin": "^0.15.2",

## Bug 类型

- [x] 其他问题

## Bug 描述
> 保密原因，截图无法提供

点击元素以后，会创建打开新的WebStorm窗口（即使已经有正在运行的IDE）
貌似是以新的用户身份打开的webstorm（打开的webstorm是没有任何用户信息的）
## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [x] mac
- [ ] linux

## 你使用的打包器及版本

- [x] webpack
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [ ] vue
- [ ] nuxt
- [x] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况): **否**
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" /> **有**

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" /> **有**

**Comment by LuckyLuoKing** [comment]
Sorry，权限问题，我用sudo打开的网页，server在执行webstorm的时候，用的是root用户，而我打开的编辑器不是root用户，close掉吧😆

**Comment by Super-LUOKI** [comment]
Sorry，权限问题，我用sudo打开的网页，server在执行webstorm的时候，用的是root用户，而我打开的编辑器不是root用户😆
