### ISSUE TITLE
插件导致 nuxt2 热更新失效

### ISSUE THREAD

**Issue by MiniOcean404** [zh-lx/code-inspector#202]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本

0.15.2、0.6.1 都有问题

## Bug 类型

其他问题

## Bug 描述

`
   if (ctx.isClient && !IS_PROD) {
        config.plugins.push(codeInspectorPlugin({ bundler: "webpack" }))
    }
`
当我在 nuxt2 中的 extend 中如上述代码添加插件后页面的 css 元素 会多出来一个 ，并且导致热更新失效，但是当我删除了这段代码它就好了

![image](https://github.com/user-attachments/assets/87866d07-535c-477a-8d7f-26ea3b035dcc)

## 系统

我认为是所有系统，但目前是 mac 发现

## 你使用的打包器及版本

webpack

## 你使用的 web 框架

nuxt.js 2

## 自检信息

是在一台机器上

**Comment by zh-lx** [comment]
未复现到你说的情况，方便的话请加群提供更详细的信息
