### ISSUE TITLE
使用Alt + Shift + 左键点击页面弹出来的是笔记本，而非vscode

### ISSUE THREAD

**Issue by Le-dawn** [zh-lx/code-inspector#205]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本

"code-inspector-plugin": "^0.13.0",
## Bug 类型
- [ ] 点击筛选框无法打开 IDE

## Bug 描述
使用Alt + Shift + 左键点击页面弹出来的是笔记本，而非vscode
笔记本如图：
![image](https://github.com/user-attachments/assets/71d1e5f0-6c6a-4b04-bae0-9b862649c6fd)

## 系统
windows 11

## 你使用的打包器及版本

- [x] webpack

## 你使用的 web 框架
- [x] react
- [x] next.js

## 自检信息

- [ ] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
答：在

- [ ] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />
答：有
![image](https://github.com/user-attachments/assets/b3c65b7e-436a-4483-960c-d81d4dc152ba)

- [ ] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />
答：有
![image](https://github.com/user-attachments/assets/21bf76b7-3d96-4bee-a979-3622fae4bc25)

**Comment by zh-lx** [comment]
参考 [指定IDE](https://inspector.fe-dev.cn/guide/ide.html) 章节，在 `.env.local` 中设置 `CODE_EDITOR=code`.
如还不生效，参考 [windows 指定 IDE 路径](https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F) 可彻底解决

**Comment by Le-dawn** [comment]
参考 [windows 指定 IDE 路径](https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F) 解决

**Comment by Le-dawn** [comment]
设置 CODE_EDITOR=code 无效

**Comment by zh-lx** [comment]
`0.17.2` 以上版本可在不设置可执行路径的情况下解决该问题
