### ISSUE TITLE
项目使用workspace聚合了多个项目，打包工具都是Vite，运行其中一个项目，使用code-inspector代码定位后报错

### ISSUE THREAD

**Issue by hebeiliujh** [zh-lx/code-inspector#211]
code-inspector-plugin": "0.16.1

## Bug 类型
点击筛选框无法打开 IDE

## Bug 描述
![image](https://github.com/user-attachments/assets/1dec8e86-4678-4fea-92a8-25be9c3f8b3c)

## 系统

- windows(未使用 wsl 虚拟机)
## 你使用的打包器及版本

- vite

## 你使用的 web 框架

- [ ] vue

## 自检信息

- 浏览器、IDE、代码是在一台机器上(非远程开发机或者云开发机情况)
- 浏览器控制台有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- 页面 DOM 是有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
Chrome 限制 ip 请求 localhost 的问题，在浏览器输入 `chrome://flags/#block-insecure-private-network-requests`，按照下图将Block insecure private network requests.项的Default改为Disabled即可。

<img width="752" alt="image" src="https://github.com/user-attachments/assets/86692a20-23a9-4dd5-bd8f-d7b0dfa9b43a">

**Comment by hebeiliujh** [comment]
感谢回复，已解决

zhoulixiang ***@***.***> 于2024年9月5日周四 14:05写道：
