### ISSUE TITLE
vite5代理不生效解决方案

### ISSUE THREAD

**Issue by ITsxy01** [zh-lx/code-inspector#212]
![Snipaste_2024-09-06_14-36-11](https://github.com/user-attachments/assets/f2b42cc5-1444-4892-8dc4-8fa18256c319)
你们这vite代理问题怎么这么麻烦,一直是代理无法代理,以前是,现在也是,如果这个功能不成熟就不要上线了,真的太浪费时间了

**Comment by zh-lx** [comment]
代理和我的插件有啥关系？？？
