### ISSUE TITLE
使用electron-vite创建的项目不支持自动打开IDE webstorm

### ISSUE THREAD

**Issue by long36708** [zh-lx/code-inspector#213]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 插件版本
0.16.1

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [x] 点击筛选框无法打开 IDE
- [ ] 其他问题

## Bug 描述

使用electron-vite创建的项目,无法打开webstorm
![image](https://github.com/user-attachments/assets/788d7e70-7724-47fe-9396-8ba02e1376ee)
![image](https://github.com/user-attachments/assets/d0c10acb-9216-4cc3-bea7-f18674eaa7f3)

## 系统

- [x] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [ ] mac
- [ ] linux

## 你使用的打包器及版本

- [ ] webpack
- [x] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [x] react
- [ ] vue
- [ ] nuxt
- [ ] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [x] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
electron-vite 默认创建的 html 文件中有如下 CSP 策略，会阻塞非同源请求(阻塞唤醒IDE的请求)，可以通过去掉该标签解决
![3bda51da54f46786a2fd0cc5828c8dc](https://github.com/user-attachments/assets/b90367c9-1e3a-4946-b710-18e0b77d4c2b)
