### ISSUE TITLE
我使用node8 vue2 好像不兼容

### ISSUE THREAD

**Issue by czh26** [zh-lx/code-inspector#215]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

**Comment by czh26** [comment]
node10以下默认不支持URLSearchParams

**Comment by zh-lx** [comment]
node8 版本太低了，升级下 node 版本吧

**Comment by czh26** [comment]
但是我们服务器上用的是node8 没办法 (泪目)

**Comment by zh-lx** [comment]
你是直接在服务器上开发吗？你可以只升级自己本机的 node 版本，服务器上打包时是生产环境不会执行该插件

**Comment by czh26** [comment]
打包的时候vue.config.js里面会报错吧

**Comment by czh26** [comment]
我试试

**Comment by czh26** [comment]
确实打包会报错

**Comment by zh-lx** [comment]
> 确实打包会报错

是指在服务器 node8 环境下打包会报错吗？这种情况的话，你需要自己写一个判断逻辑，在服务器打包环境中，不要将插件添加到 webpack plugins 中

**Comment by czh26** [comment]
好的 但是他还有别的错误  比如在打包后的文件index.umd.js里找不到close这个方法

**Comment by zh-lx** [comment]
> 好的 但是他还有别的错误 我换成node16后 node_modules里打包的文件index.umd.js里找不到close这个方法

理论上打包时你不把这个插件添加进 plugins 中，就不应该有插件的内容了吧？看下你的判断逻辑是怎么写的呢？

**Comment by czh26** [comment]
这个我表述的有问题  应该是 node_modules 里该插件的dist文件下的index.umd.js里找不到close这个方法
![Uploading 1727078673966.png…]()

**Comment by czh26** [comment]
这个是我本地的报错内容

**Comment by czh26** [comment]
运行vue-cli-service serve时报的错误

**Comment by zh-lx** [comment]
> 运行vue-cli-service serve时报的错误

运行这个的 node 版本是多少

**Comment by zh-lx** [comment]
加群或者微信聊吧，这里提供的信息太少，不好给你诊断

**Comment by czh26** [comment]
const WebpackCodeInspectorPlugin = require('webpack-code-inspector-plugin')
chainWebpack: (config) => {
    config
      .plugin('webpack-code-inspector-plugin')
      .use(new WebpackCodeInspectorPlugin());
  }
  类似这样 node 16.20.0

**Comment by czh26** [comment]
好的 我加您微信

**Comment by zh-lx** [comment]
> const WebpackCodeInspectorPlugin = require('webpack-code-inspector-plugin') chainWebpack: (config) => { config .plugin('webpack-code-inspector-plugin') .use(new WebpackCodeInspectorPlugin()); } 类似这样 node 16.20.0

这个是很老的版本了，你按照新的文档去使用
