### ISSUE TITLE
Not opening editor (idea) on macos

### ISSUE THREAD

**Issue by ioma8** [zh-lx/code-inspector#216]
I wanted to use it to open intellij idea on my macos using this tool, hovewer it doesnt work. I also directly put the executable path into the CODE_EDITOR in .env.local. Still doesnt do anything. No errors in the console as well.

**Comment by zh-lx** [comment]
> I wanted to use it to open intellij idea on my macos using this tool, hovewer it doesnt work. I also directly put the executable path into the CODE_EDITOR in .env.local. Still doesnt do anything. No errors in the console as well.

Just can't open IDEA? Is there is a tip in your browser's console as following?:
<img width="884" alt="image" src="https://github.com/user-attachments/assets/3d0957c1-7d72-4ab8-9a48-2403ee244762">

**Comment by DrBearZay** [comment]
我无法打开vscode，chrome控制台没有任何报错，vscode终端的报错如下。我按照提示进行了操作但是仍然无法正常使用
![Snipaste_2024-09-27_17-40-24](https://github.com/user-attachments/assets/9d779754-8d67-4e3b-87ee-def702a7e6c4)

**Comment by zh-lx** [comment]
> 我无法打开vscode，chrome控制台没有任何报错，vscode终端的报错如下。我按照提示进行了操作但是仍然无法正常使用 ![Snipaste_2024-09-27_17-40-24](https://private-user-images.githubusercontent.com/169366348/371479328-9d779754-8d67-4e3b-87ee-def702a7e6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzA0NjgsIm5iZiI6MTcyNzQzMDE2OCwicGF0aCI6Ii8xNjkzNjYzNDgvMzcxNDc5MzI4LTlkNzc5NzU0LThkNjctNGUzYi04N2VlLWRlZjcwMmE3ZTZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwOTQyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2ZlN2FlNTgzNjM0MmYwMDQ2ODAyYjA1ZDY4NzJlNGJjYWEyNTdmOTVhYjMwZjBlOWFhM2Y2ZTY0OGFhZjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cr0ztG2yfZxWOalGmfng_EGq6oRMIMCAtL_f7dMXWfQ)

你的问题可以通过 [指定可执行路径](https://inspector.fe-dev.cn/guide/ide.html#mac-%E7%B3%BB%E7%BB%9F) 来解决试试

**Comment by DrBearZay** [comment]
已解决，感谢
