### ISSUE TITLE
Next.js hideDomPathAttr cause hydrate error

### ISSUE THREAD

**Issue by tjx666** [zh-lx/code-inspector#217]
## 插件版本

^0.16.1

## Bug 类型

- [ ] 安装插件后启动项目编译失败
- [ ] 按住组合键无筛选框
- [ ] 点击筛选框无法打开 IDE
- [x] 其他问题

## Bug 描述

online reproduce: https://stackblitz.com/github/tjx666/next-code-inspect-issue?file=README.md

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/806e7555-379d-4b91-a497-c0ddb630e674">

<details>
<summary>Chrome devtools console error </summary>

A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <Router actionQueue={{state:{...}, ...}} assetPrefix="">
      <HistoryUpdater>
      <RuntimeStyles>
      <HotReload assetPrefix="">
        <ReactDevOverlay onReactError={function} state={{nextId:1, ...}} dispatcher={{...}}>
          <DevRootNotFoundBoundary>
            <NotFoundBoundary notFound={<NotAllowedRootNotFoundError>}>
              <NotFoundErrorBoundary pathname="/" notFound={<NotAllowedRootNotFoundError>} notFoundStyles={undefined} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <Segment>
                      <link>
                      <RootLayout>
                        <html
                          lang="en"
+                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/layout.tsx:27:5:html"
-                         data-insp-path={null}
                        >
                          <body
                            className="__variable_1e4310 __variable_c3aa02 antialiased"
+                           data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/layout.tsx:28:7:body"
-                           data-insp-path={null}
                          >
                            ...
                              <Segment>
                                <Home>
                                  <div
                                    className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-..."
+                                   data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:5:5:div"
-                                   data-insp-path={null}
                                  >
                                    <main
                                      className="flex flex-col gap-8 row-start-2 items-center sm:items-start"
+                                     data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:6:7:..."
-                                     data-insp-path={null}
                                    >
                                      <img
                                        alt="Next.js logo"
+                                       data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:7:..."
-                                       data-insp-path={null}
                                        fetchPriority={undefined}
                                        loading={undefined}
                                        width={180}
                                        height={38}
                                        decoding="async"
                                        data-nimg="1"
                                        className="dark:invert"
                                        style={{color:"transparent"}}
                                        sizes={undefined}
                                        srcSet={undefined}
                                        src="/next.svg"
                                        ref={function}
                                        onLoad={function onLoad}
                                        onError={function onError}
                                      >
                                      ...
                                      <ol
                                        className="list-inside list-decimal text-sm text-center sm:text-left font-[fam..."
+                                       data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:15..."
-                                       data-insp-path={null}
                                      >
                                        <li
                                          className="mb-2"
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                        >
                                          <code
                                            className="bg-black/[.05] dark:bg-white/[.06] px-1 py-0.5 rounded font-sem..."
+                                           data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.ts..."
-                                           data-insp-path={null}
                                          >
+                                           app/page.tsx
                                          ...
                                        <li
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                        >
+                                         Save and see your changes instantly.
                                      <div
                                        className="flex gap-4 items-center flex-col sm:flex-row"
+                                       data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:26..."
-                                       data-insp-path={null}
                                      >
                                        <a
                                          className="rounded-full border border-solid border-transparent transition-co..."
                                          href={"https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-..."}
                                          target="_blank"
                                          rel="noopener noreferrer"
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                        >
                                          <img
                                            alt="Vercel logomark"
+                                           data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.ts..."
-                                           data-insp-path={null}
                                            fetchPriority={undefined}
                                            loading="lazy"
                                            width={20}
                                            height={20}
                                            decoding="async"
                                            data-nimg="1"
                                            className="dark:invert"
                                            style={{color:"transparent"}}
                                            sizes={undefined}
                                            srcSet={undefined}
                                            src="/vercel.svg"
                                            ref={function}
                                            onLoad={function onLoad}
                                            onError={function onError}
                                          >
                                          ...
                                        <a
                                          className="rounded-full border border-solid border-black/[.08] dark:border-w..."
                                          href={"https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir..."}
                                          target="_blank"
                                          rel="noopener noreferrer"
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                        >
+                                         Read our docs
                                    <footer
                                      className="row-start-3 flex gap-6 flex-wrap items-center justify-center"
+                                     data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:52:7..."
-                                     data-insp-path={null}
                                    >
                                      <a
                                        className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                                        href={"https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-..."}
                                        target="_blank"
                                        rel="noopener noreferrer"
+                                       data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:53..."
-                                       data-insp-path={null}
                                      >
                                        <img
                                          aria-hidden={true}
                                          alt="File icon"
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                          fetchPriority={undefined}
                                          loading="lazy"
                                          width={16}
                                          height={16}
                                          decoding="async"
                                          data-nimg="1"
                                          className={undefined}
                                          style={{color:"transparent"}}
                                          sizes={undefined}
                                          srcSet={undefined}
                                          src="/file.svg"
                                          ref={function}
                                          onLoad={function onLoad}
                                          onError={function onError}
                                        >
                                        ...
                                      <a
                                        className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                                        href={"https://vercel.com/templates?framework=next.js&utm_source=create-next-..."}
                                        target="_blank"
                                        rel="noopener noreferrer"
+                                       data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:68..."
-                                       data-insp-path={null}
                                      >
                                        <img
                                          aria-hidden={true}
                                          alt="Window icon"
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                          fetchPriority={undefined}
                                          loading="lazy"
                                          width={16}
                                          height={16}
                                          decoding="async"
                                          data-nimg="1"
                                          className={undefined}
                                          style={{color:"transparent"}}
                                          sizes={undefined}
                                          srcSet={undefined}
                                          src="/window.svg"
                                          ref={function}
                                          onLoad={function onLoad}
                                          onError={function onError}
                                        >
                                        ...
                                      <a
                                        className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                                        href={"https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-templa..."}
                                        target="_blank"
                                        rel="noopener noreferrer"
+                                       data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:83..."
-                                       data-insp-path={null}
                                      >
                                        <img
                                          aria-hidden={true}
                                          alt="Globe icon"
+                                         data-insp-path="/Users/yutengjing/code/next-code-inspect-issue/app/page.tsx:..."
-                                         data-insp-path={null}
                                          fetchPriority={undefined}
                                          loading="lazy"
                                          width={16}
                                          height={16}
                                          decoding="async"
                                          data-nimg="1"
                                          className={undefined}
                                          style={{color:"transparent"}}
                                          sizes={undefined}
                                          srcSet={undefined}
                                          src="/globe.svg"
                                          ref={function}
                                          onLoad={function onLoad}
                                          onError={function onError}
                                        >
                                        ...
                    ...
          ...

</details>

## 系统

- [ ] windows(未使用 wsl 虚拟机)
- [ ] windows(使用了 wsl 虚拟机)
- [x] mac
- [ ] linux

## 你使用的打包器及版本

- [x] webpack
- [ ] vite
- [ ] rspack
- [ ] umijs
- [ ] 其他

## 你使用的 web 框架

- [ ] react
- [ ] vue
- [ ] nuxt
- [x] next.js
- [ ] svelte
- [ ] astro
- [ ] solid
- [ ] preact
- [ ] qwik
- [ ] 其他

## 自检信息

- [ ] 你的浏览器、IDE、代码是否在一台机器上(非远程开发机或者云开发机情况)
- [x] 浏览器控制台是否有打印组合按键提示信息<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/77bcef30-88a5-4f58-b306-a92e01ecef8f" width="500" />

- [x] 页面 DOM 是否有注入 `data-insp-path` 属性<br />
      <img src="https://github.com/zh-lx/code-inspector/assets/73059627/0523f9fb-e755-4561-9284-8970e4081bcc" width="600" />

**Comment by zh-lx** [comment]
感谢反馈，这是个已知问题目前无法解决，建议勿在 nextjs 中使用该特性

**Comment by zh-lx** [comment]
@tjx666 已在 `0.16.2` 版本中修复该问题，欢迎安装体验

**Comment by tjx666** [comment]
@zh-lx awesome!

**Comment by tjx666** [comment]
最新版本 nextjs 不行：

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/e09625ca-560a-443c-8e20-b1a322f40423">

```
"next": "15.0.0-canary.200"
"code-inspector-plugin": "^0.17.2",
```

@zh-lx

**Comment by zh-lx** [comment]
> 最新版本 nextjs 不行：
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/41773861/378177385-e09625ca-560a-443c-8e20-b1a322f40423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjQ5NjksIm5iZiI6MTcyOTU2NDY2OSwicGF0aCI6Ii80MTc3Mzg2MS8zNzgxNzczODUtZTA5NjI1Y2EtNTYwYS00NDNjLThlMjAtYjFhMzIyZjQwNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAyMzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZWZmZDE3YTJlNDIxOWY1YzNhN2FlYWQ4YTg3ODMyY2RhYjY2MGRhMmQ3N2I1MTk4ODQ5YTY3ZWMwZTJhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ygFLxpwv6NgU6S9KUWGq_yWZGlNxuWHWAD20jesJLw">
> ```
> "next": "15.0.0-canary.200"
> "code-inspector-plugin": "^0.17.2",
> ```
> 
> @zh-lx

已在 `0.17.3` 版本中支持了最新版本
