### ISSUE TITLE
MPA 项目只会在第一个页面生效

### ISSUE THREAD

**Issue by zh-lx** [zh-lx/code-inspector#228]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## 功能描述

MPA 项目只会在第一个页面生效

**Comment by zh-lx** [comment]
已在 `0.17.4` 及以上版本中解决了该问题

**Comment by sweetwisdom** [comment]
项目地址： https://github.com/sweetwisdom/react-mpa-page
rspack的mpa项目 只在第一个页面生效

<img width="2000" height="644" alt="Image" src="https://github.com/user-attachments/assets/3bc0d6d0-af10-422e-8d5b-65163d1fa5cf" />
