### ISSUE TITLE
期望 代码审查开关按钮 默认位置调整，同时支持下移动端拖拽

### ISSUE THREAD

**Issue by Djj520Ztm** [zh-lx/code-inspector#236]
移动端使用代码审查开关 定位代码时，发现开关位置居顶部，在手机上被遮挡点不到，所以希望调整默认位置，同时可以支持移动端拖拽

**Comment by zh-lx** [comment]
已在 `0.17.9` 版本中优化了移动端交互，欢迎安装新版本体验
