### ISSUE TITLE
使用cursor打开项目代码跳转不准确

### ISSUE THREAD

**Issue by nullandundefined** [zh-lx/code-inspector#252]
> 提示：如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息
使用cursor打开项目的代码，然后在网页点击元素，有时候只可以跳转到对应的代码文件的首行，无法像vscode一样定位到具体的代码行数。

**Comment by zh-lx** [comment]
请提供一些详细信息
