### ISSUE TITLE
点击后怎么跳转到webstorm内。

### ISSUE THREAD

**Issue by lnts2015** [zh-lx/code-inspector#28]
点击后怎么跳转到webstorm内vue页， webstorm内需要怎么配置。 现在没有配置的情况下，自动跳转到vscode。

谢谢

**Comment by zh-lx** [comment]
会自动识别运行中的编译器，只要关闭 vscode 并且不要在 `.env.local` 里面配置 `CODE_EDITOR=code` 就能自动识别 webstorm 并打开
