### ISSUE TITLE
可以考虑出个浏览器插件

### ISSUE THREAD

**Issue by xch1029** [zh-lx/code-inspector#30]

**Comment by Kerinlin** [comment]
<img width="1428" alt="image" src="https://github.com/zh-lx/code-inspector/assets/32203226/e2909085-2454-493c-a57e-6ec470b638e4">
浏览器里面有一个工作区，可以直接传本地项目源码，但是我不知道插件能不能拿到这里的代码

**Comment by zh-lx** [comment]
> <img alt="image" width="1428" src="https://user-images.githubusercontent.com/32203226/246375535-e2909085-2454-493c-a57e-6ec470b638e4.png"> 浏览器里面有一个工作区，可以直接传本地项目源码，但是我不知道插件能不能拿到这里的代码

这个也不行，这里找不到源码和 dom 对应的关系，对应关系的构建目前必须在编译阶段去做

**Comment by hqzh** [comment]
点击控制台报错跳转到代码可以考虑实现一下

**Comment by xch1029** [comment]
@zh-lx  https://github.com/infi-pc/locatorjs 看下这个库和你的实现是否一致

**Comment by zh-lx** [comment]
> @zh-lx https://github.com/infi-pc/locatorjs 看下这个库和你的实现是否一致

实现思路上看起来有些相似，但是我实际体验了下这个浏览器插件有俩问题：无法定位
