### ISSUE TITLE
安装以后启动开发环境报错 Illegal tag name

### ISSUE THREAD

**Issue by lebronjs** [zh-lx/code-inspector#31]
`Syntax Error: SyntaxError: Illegal tag name. Use '&lt;' to print '<'`

**Comment by zh-lx** [comment]
方便说一下系统 (MAC/windows)、打包工具(vite/webpack)以及版本，vue的版本分别是什么吗

**Comment by lebronjs** [comment]
"vue": "^2.6.10"
webpack@4.43.0

MAC

**Comment by zh-lx** [comment]
有使用 jsx 语法吗

**Comment by lebronjs** [comment]
> 

有

**Comment by zh-lx** [comment]
> > 
> 
> 有

刚刚修复了一个 vue2 jsx 的错误，不确定有没有解决你这个问题，你安装 `0.0.11` 版本试试还有这个问题吗
