### ISSUE TITLE
页面上会始终呈现一个 click to open editor 的小框

### ISSUE THREAD

**Issue by 1070152533** [zh-lx/code-inspector#32]
页面上会始终呈现一个 click to open editor 的小框

经过判断是页面上这个元素code-inspector-component呈现的
十分抱歉，由于公司网络原因无法截图

webpack-code-inspector-plugin 0.0.10
nodejs  14.21.3
npm  6.14.18
operation  win10
webpack 4.46.0
vue 3.2.39

**Comment by 1070152533** [comment]
没有进行任何配置，刚刚我有尝试着进行配置，在`npm watch` 跑完之后，仍然出现了那个框

`npm watch`对应的实际执行为`"watch": "set NODE_ENV=local && vue-cli-service build --watch"`

```

    chainWebpack: (config) => {
        config.plugins.delete('prefetch'); // 关闭prefetch（prefetch will request all files backgound, no need do this
        //文件路径设置别名
        config.resolve.alias
            .set('request', resolve('src/utils/request.js'))
            .set('httpUrl', resolve('src/utils/UrlUtils'))
            .set('commonUtils', resolve('src/utils/commonUtils'))
        config.resolve.symlinks(false);
        config.resolve.alias.set('vue', path.resolve('./node_modules/vue'));
        config
            .plugin('webpack-code-inspector-plugin')
            .use(new WebpackCodeInspectorPlugin({
                showSwitch: false
            }));
    },
```

**Comment by 1070152533** [comment]
> @1070152533 配置里的showSwitch 没有设置成true吧？ <img alt="image" width="1035" src="https://user-images.githubusercontent.com/6037915/246384839-7fb79115-dde0-4904-8524-10e86dcafc48.png">

我等会下班回去后，看看在自己的工程上能否复现

**Comment by zh-lx** [comment]
请问浏览器的型号和版本是多少呢？

**Comment by 1070152533** [comment]
> 请问浏览器的型号和版本是多少呢？

chrome 版本 114.0.5735.134（正式版本） （64 位）

**Comment by 1070152533** [comment]
由于工程是vue-cli构建的vue2项目后续升级到vue3的，我昨天把所有的依赖整理了一遍，清理了大部分无用依赖并升级依赖后，奇迹般的恢复正常了，所以这并非这个工具的问题导致的，盲猜是个兼容问题

**Comment by zh-lx** [comment]
> 由于工程是vue-cli构建的vue2项目后续升级到vue3的，我昨天把所有的依赖整理了一遍，清理了大部分无用依赖并升级依赖后，奇迹般的恢复正常了，所以这并非这个工具的问题导致的，盲猜是个兼容问题

好嘞，也感谢反馈
