### ISSUE TITLE
插件会导致页面空白

### ISSUE THREAD

**Issue by sigma-plus** [zh-lx/code-inspector#34]
现象：在 https://github.com/honghuangdc/soybean-admin 开源项目的基础上，引入本插件。点击任意导航栏，组件都无法正常加载，页面为空白。但是此时F5刷新页面后，页面恢复正常。

原因：猜测是多个根节点导致，因为之前版本一直报这个warning。

**Comment by koukouzaki** [comment]
同样有此问题，路由跳转后显示空白
