### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by amxsa** [zh-lx/code-inspector#40]
npm i code-inspector-plugin -D
Debugger attached.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://mirrors.huaweicloud.com/repository/npm/code-inspector-plugin
npm ERR! 404 
npm ERR! 404  'code-inspector-plugin@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by amxsa** [comment]
文档写的不清不楚...

**Comment by zh-lx** [comment]
我昨天发的包，华为云的 npm 镜像同步太慢了没同步，换 npm 官方源或者 taobao 源可以安装
