### ISSUE TITLE
VScode 点击元素没有定位到,提示错误

### ISSUE THREAD

**Issue by xin12023** [zh-lx/code-inspector#50]
'wmic' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
Failed to recognize IDE automatically, add something like CODE_EDITOR=code to the .env.local file in your project folder, or add editor: "code" to CodeInspectorPlugin config, and then restart the development server. Learn more: https://goo.gl/MMTaZt

windows  vscode 
插件版本  0.1.12

**Comment by xin12023** [comment]
路径中没有中文

**Comment by zh-lx** [comment]
感谢反馈，可能与您的系统或者编辑器有关，需要更多具体信息定位，方便加入用户群或者添加我的好友方便进一步定位吗

**Comment by biaogeshuihuo** [comment]
请问解决了没有 , 如果解决了 , 是如何解决的呢?

**Comment by zh-lx** [comment]
> 请问解决了没有 , 如果解决了 , 是如何解决的呢?

已解决，更新插件至最新版本即可。如果不生效，可参考 [指定IDE](https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F) 设置 vscode 的可执行路径
