### ISSUE TITLE
wsl 环境 vite项目无法跳转

### ISSUE THREAD

**Issue by jackieZhouQQ** [zh-lx/code-inspector#60]
![image](https://github.com/zh-lx/code-inspector/assets/108133430/3d7e7ffa-6caf-4f38-bc54-e6aa9d06803f)
按照要求设置.env.local也不行，按住组合键时在页面有 DOM 遮罩筛选，不会打开vscode源码

**Comment by zh-lx** [comment]
嗯，是因为插件在项目运行时，会启动一个本地 `localhost` 端口，用于浏览器点击时向这个端口发送请求，通知打开 vscode。而 wsl 的端口是运行在虚拟机上的，我会适配一下，方便的话可以加一下 readme 里面我的微信，等我适配好了通知您测试一下

**Comment by zh-lx** [comment]
已在 `0.3.2` 版本中修复了该问题，请安装 `0.3.2` 版本体验使用

**Comment by jackieZhouQQ** [comment]
wsl安装0.3.2 ps相关的提示没了，但还是不会跳转编辑器
![image](https://github.com/zh-lx/code-inspector/assets/108133430/eae50cb3-5308-41f1-8dcd-a511d99edcfa)

**Comment by jackieZhouQQ** [comment]
@zh-lx

**Comment by zh-lx** [comment]
> @zh-lx

好的，

> wsl安装0.3.2 ps相关的提示没了，但还是不会跳转编辑器 ![image](https://private-user-images.githubusercontent.com/108133430/293323344-eae50cb3-5308-41f1-8dcd-a511d99edcfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzQyNzksIm5iZiI6MTcwMzgzMzk3OSwicGF0aCI6Ii8xMDgxMzM0MzAvMjkzMzIzMzQ0LWVhZTUwY2IzLTUzMDgtNDFmMS04ZGNkLWE1MTFkOTllZGNmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNzEyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzEyYWNhNDY4OTM3MzJkZmI3N2U3MjhjN2E0ZjgxMzA4NTI5NGQxN2I3Y2MwYzQxNmNjNjJkYTAzYWQxZjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vCmuWSjw5nJQUkQgeDdV_WFLOcRPoi2gRRV_qAALKYk)

好的，看起来 wsl 还需要单独兼容一下，我再看一下哈

**Comment by zh-lx** [comment]
> wsl安装0.3.2 ps相关的提示没了，但还是不会跳转编辑器 ![image](https://private-user-images.githubusercontent.com/108133430/293323344-eae50cb3-5308-41f1-8dcd-a511d99edcfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzQ1ODksIm5iZiI6MTcwMzgzNDI4OSwicGF0aCI6Ii8xMDgxMzM0MzAvMjkzMzIzMzQ0LWVhZTUwY2IzLTUzMDgtNDFmMS04ZGNkLWE1MTFkOTllZGNmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNzE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTg4MTY3Mzk2ZTdjMmM4MjU5MjNlODIxMWRmNTJmNTIwNmUxMTMyNjdkNDg0ODdjMDM4NTM0MTYxMzQ4YmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhW_m-rBB0lNvLf6ZoPI79hN8ZBy1rKQRjUX4MNnBM0)

好的，看起来 wsl 中编辑器的指令和标准 linux 不完全相同，我这两天装一个 wsl 适配一下

**Comment by jackieZhouQQ** [comment]
大佬，啥时候能修复呀

**Comment by zh-lx** [comment]
预计2.10 之前

**Comment by zh-lx** [comment]
@jackieZhouQQ 针对你的 wsl 环境适配比较麻烦些，请问方便加群或者微信方便跟进信息部

**Comment by jackieZhouQQ** [comment]
可以啊，群号多少



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月4日(周日) 晚上10:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zh-lx/code-inspector] wsl 环境 vite项目无法跳转 (Issue #60)




 
@jackieZhouQQ 针对你的 wsl 环境适配比较麻烦些，请问方便加群或者微信方便跟进信息不

**Comment by zh-lx** [comment]
> 可以啊，群号多少
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月4日(周日) 晚上10:49 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zh-lx/code-inspector] wsl 环境 vite项目无法跳转 (Issue #60) @jackieZhouQQ 针对你的 wsl 环境适配比较麻烦些，请问方便加群或者微信方便跟进信息不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

在 Readme.md 最后分别有 qq 群和微信群

**Comment by gxr404** [comment]
应该是wsl内层系统找不到外层window的code程序，
估计得在wsl中内层系统配置环境变量，
按作者文档里的只是配了window的环境变量

- https://blog.csdn.net/weixin_44089259/article/details/127052047
-  https://www.51cto.com/article/624773.html

**Comment by zh-lx** [comment]
由于 wsl 中的代码服务和 windows 的 vscode 不在一个环境中，无法识别系统运行的 IDE，需要再 `.env.local` 手动添加 IDE 配置，总结下目前有两种方案支持：

### 第一种
设置 ide 的路径为 remote 的 code 路径
![image](https://github.com/zh-lx/code-inspector/assets/73059627/2c492b33-613b-46c5-aed9-1d50bae88e7b)

### 第二种

参照 [其他IDE](https://inspector.fe-dev.cn/guide/ide.html#windows-%E7%B3%BB%E7%BB%9F) 一节找到 windows vscode 的可执行路径，设置 `.env.local` 如下：
```perl
CODE_EDITOR=IDE可执行路径
CODE_INSPECTOR_FORMAT_PATH=["-g", "-r", "//wsl.localhost/Ubuntu{file}:{line}:{column}"]
```

**Comment by zh-lx** [comment]
参考 #144 
可以通过在wsl中使用 `which code` 找到vscode remote的地址，地址差不多长这样，将其设置 `CODE_EDITOR` 的值
```
/home/xxx/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/remote-cli/code
```
