### ISSUE TITLE
支持强制在当前vscode打开文件

### ISSUE THREAD

**Issue by jan-bar** [zh-lx/code-inspector#61]
因为我设置vscode在新窗口打开文件`"window.openFilesInNewWindow": "on",`，因此在使用该插件时会打开一个新的窗口。但实际上vscode的命令行有提供参数强制在当前编辑器打开：`code -r xxx.ts`

![image](https://github.com/zh-lx/code-inspector/assets/14202095/63871751-e6cd-482f-a711-da8a3a4666ce)

我觉得可以加个参数配置一下，不然我还得修改vscode的配置额。要是`code`命令的所有参数都支持配置那就更好了。

**Comment by zh-lx** [comment]
感谢反馈，近期我补充一下❤

**Comment by zh-lx** [comment]
在 `0.8.0-beta.1` 版本中增加了 `openIn` 参数，设置 `reuse` 可以复用当前窗口
https://inspector.fe-dev.cn/guide/api.html#openin
