### ISSUE TITLE
element-plus的国际化组件添加该插件的属性报警告

### ISSUE THREAD

**Issue by jan-bar** [zh-lx/code-inspector#73]
![image](https://github.com/zh-lx/code-inspector/assets/14202095/50d8badd-c01b-452c-8067-f5be2f9cc2c6)

如上图所示，会不会有其他框架也存在这种问题，虽然只是开发时的警告，但还是希望有办法去掉。比如增加配置，哪些组件不添加属性

**Comment by zh-lx** [comment]
已在 `0.4.5` 版本中修复了此问题，不需要用户手动配置，直接在底层 warning 中消除了关于 `data-insp-path` 这个的报错，欢迎安装新版本体验

**Comment by jan-bar** [comment]
@zh-lx 已更新，问题解决了，点赞。
