### ISSUE TITLE
monorepo 本地优化

### ISSUE THREAD

**Issue by jo0ger** [zh-lx/code-inspector#77]
现在我的仓库是 Monorepo 的，比如要本地启动 packages/A，现在 A 是 import 了 B 的，需要能够在页面上 跳转到 packages/B 的 代码里

因为 monorepo 在 yarn install 的时候把 packages 下的模块 symlink 到了 node_modules 下，所以现在是不支持跳转到 B 里的，

另外还需要映射到 packages B 的真实路径 pacakges/B/src/xxx，而不是 node_modules/B/src/xxx

**Comment by zh-lx** [comment]
收到，近期我看下这种场景

**Comment by zh-lx** [comment]
symlink 到了 node_modules，对于这种情况定位到 node_modules 中是合理的，暂无法解决

**Comment by jo0ger** [comment]
@zh-lx 我是通过这样解决了

把 webpack plugin 里的 loader 的配置里的 exclude 改一下
https://github.com/zh-lx/code-inspector/blob/main/packages/webpack-plugin/src/index.ts#L34
https://github.com/zh-lx/code-inspector/blob/main/packages/webpack-plugin/src/index.ts#L48

```ts
{
    exclude: /node_modules\/(?!(@scope1|@scope2)\/).*/
}
```

**Comment by zh-lx** [comment]
可以可以，我往文档中记一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月26日 14:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zh-lx/code-inspector] monorepo 本地优化 (Issue #77) |

@zh-lx 我是通过这样解决了

把 webpack plugin 里的 loader 的配置里的 exclude 改一下
https://github.com/zh-lx/code-inspector/blob/main/packages/webpack-plugin/src/index.ts#L34
https://github.com/zh-lx/code-inspector/blob/main/packages/webpack-plugin/src/index.ts#L48

{exclude: ***@***.******@***.***)\/).*/}

**Comment by zh-lx** [comment]
@jo0ger 我在 `0.18.1` 版本针对你说的这种 monorepo 的情况做了优化，你可以通过 [include](https://inspector.fe-dev.cn/api/advance.html#include) 配置解决这个问题，搭配 [mappings](https://inspector.fe-dev.cn/api/advance.html#mappings) 使用更佳
