### ISSUE TITLE
支持自定义开发环境的判断

### ISSUE THREAD

**Issue by wjf2016** [zh-lx/code-inspector#79]
请问兼容webpack3吗？我的一个webpack3项目引入了这个插件，但不起作用，浏览器控制台也没有快捷键提示。

**Comment by zh-lx** [comment]
兼容的，我刚刚在一个 webpack 3.3.0 的项目中测试了一下也没问题，可以加 Readme 里面我的微信帮你详细定位一下问题

**Comment by wjf2016** [comment]
> 兼容的，我刚刚在一个 webpack 3.3.0 的项目中测试了一下也没问题，可以加 Readme 里面我的微信帮你详细定位一下问题

感谢回复，我已经找到原因了。通过阅读插件源码，发现判断开发环境的逻辑是这样子的
```js
    // 仅在开发环境下使用
    if (
      compiler?.options?.mode !== 'development' &&
      process.env.NODE_ENV !== 'development'
    ) {
      return;
    }
```
两个条件必须同时满足，而我的项目在开发模式下，process.env.NODE_ENV的值是undefined，导致插件没有工作。我的项目启动开发模式的脚本为：
 "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js"

对此，有两个解决方法：
1、修改项目，在开发模式下，手动设置process.env.NODE_ENV的值为development
2、插件判断开发环境的逻辑是否需要优化？因为并不是所有项目开发模式下process.env.NODE_ENV的值都是development，我认为仅用compiler?.options?.mode !== 'development'判断就可以了

**Comment by zh-lx** [comment]
> > 兼容的，我刚刚在一个 webpack 3.3.0 的项目中测试了一下也没问题，可以加 Readme 里面我的微信帮你详细定位一下问题
> 
> 感谢回复，我已经找到原因了。通过阅读插件源码，发现判断开发环境的逻辑是这样子的
> 
> ```js
>     // 仅在开发环境下使用
>     if (
>       compiler?.options?.mode !== 'development' &&
>       process.env.NODE_ENV !== 'development'
>     ) {
>       return;
>     }
> ```
> 
> 两个条件必须同时满足，而我的项目在开发模式下，process.env.NODE_ENV的值是undefined，导致插件没有工作。我的项目启动开发模式的脚本为： "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js"
> 
> 对此，有两个解决方法： 1、修改项目，在开发模式下，手动设置process.env.NODE_ENV的值为development 2、插件判断开发环境的逻辑是否需要优化？因为并不是所有项目开发模式下process.env.NODE_ENV的值都是development，我认为仅用compiler?.options?.mode !== 'development'判断就可以了

这段代码是两个条件都不满足的时候才不会生效，估计是 webpack3 不兼容 `compiler?.options?.mode`，同时你的项目 `process.env.NODE_ENV` 的值不为 `development`，两个条件都不满足所以没触发。我今天升级下，加一个 `dev` 的配置项吧，允许用户手动设置 dev 环境的判断

**Comment by wjf2016** [comment]
> > > 兼容的，我刚刚在一个 webpack 3.3.0 的项目中测试了一下也没问题，可以加 Readme 里面我的微信帮你详细定位一下问题
> > 
> > 
> > 感谢回复，我已经找到原因了。通过阅读插件源码，发现判断开发环境的逻辑是这样子的
> > ```js
> >     // 仅在开发环境下使用
> >     if (
> >       compiler?.options?.mode !== 'development' &&
> >       process.env.NODE_ENV !== 'development'
> >     ) {
> >       return;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 两个条件必须同时满足，而我的项目在开发模式下，process.env.NODE_ENV的值是undefined，导致插件没有工作。我的项目启动开发模式的脚本为： "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js"
> > 对此，有两个解决方法： 1、修改项目，在开发模式下，手动设置process.env.NODE_ENV的值为development 2、插件判断开发环境的逻辑是否需要优化？因为并不是所有项目开发模式下process.env.NODE_ENV的值都是development，我认为仅用compiler?.options?.mode !== 'development'判断就可以了
> 
> 这段代码是两个条件都不满足的时候才不会生效，估计是 webpack3 不兼容 `compiler?.options?.mode`，同时你的项目 `process.env.NODE_ENV` 的值不为 `development`，两个条件都不满足所以没触发。我今天升级下，加一个 `dev` 的配置项吧，允许用户手动设置 dev 环境的判断

是的，我看走眼了，确实是两个条件都不满足的时候才不会生效，我的情况就是两个条件都不满足，然后我手动修改process.env.NODE_ENV的值为development就满足条件了。赞同加dev配置项，有dev的时候以dev的值为准，没有再由插件自行判断。dev的类型建议为function，插件执行function获取返回值，如果返回值是true说明就是dev环境
```js
    CodeInspectorPlugin({
      bundler: 'webpack',
      dev: () => {
        // do something
        return true
      },
    }),
```

**Comment by zh-lx** [comment]
在 #83 中解决了该问题，新增了 `dev` 参数，支持传 `boolean` 类型也支持传函数类型返回一个 `boolean`，可以安装 `0.5.0` 版本体验下
