### ISSUE TITLE
请问为什么 inject-loader 要关闭 cache？可以提供参数控制吗

### ISSUE THREAD

**Issue by iworkerweb** [zh-lx/code-inspector#80]
![图片](https://github.com/zh-lx/code-inspector/assets/35645410/6d31c875-9a04-45b5-b6f0-095a11d13a7c)

本地开发，修改文件，然后保存，loader花费时间比较长
![图片](https://github.com/zh-lx/code-inspector/assets/35645410/da7a8997-8a2d-460f-ad19-406b60224cbf)

开启cache后，修改文件，然后保存，花费时间
![图片](https://github.com/zh-lx/code-inspector/assets/35645410/00eabd28-62f3-4e02-a7c8-b49c645be42b)

**Comment by zh-lx** [comment]
> ![图片](https://private-user-images.githubusercontent.com/35645410/299152815-f152933a-914c-4491-b70e-2196d3f60c33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjI0NzYsIm5iZiI6MTcwNjA2MjE3NiwicGF0aCI6Ii8zNTY0NTQxMC8yOTkxNTI4MTUtZjE1MjkzM2EtOTE0Yy00NDkxLWI3MGUtMjE5NmQzZjYwYzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWJmNTc1NGMzYTVmZmRmY2VjYTRmMjRhMWM2NTQxNTkwOTE4ZDlmOTRlYzZiNzAzNzkyMDNhYjJjMWQyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYEi2y6xkrgC2tUjSSPQIYN-rSGEl36ItZtkblZk2_4) 感觉还是有些慢

看起来有大幅提升了哈，我看看这周再支持下用户自定义入口文件以及编译文件试试

**Comment by iworkerweb** [comment]
是的 感谢  那你们升级后 我再试试

**Comment by zh-lx** [comment]
在 `0.5.0` 版本中新增了 [forceinjectcache](https://inspector.fe-dev.cn/guide/api.html#forceinjectcache) 参数可以使用，可以安装体验下

**Comment by jo0ger** [comment]
@zh-lx 我加了这个插件，0.5 的版本，并且没有设置 forceInjectcache 这个参数，HMR 好慢呀

这是加之前的
<img width="365" alt="image" src="https://github.com/zh-lx/code-inspector/assets/16385416/cb8f961b-5590-43f7-bccb-c23a0456bddd">

这是加之后的
<img width="362" alt="企业微信截图_0dfd520a-3266-4fe9-a2c7-e2e92cc47cf2" src="https://github.com/zh-lx/code-inspector/assets/16385416/76a8c65e-7edc-41e9-80a9-6f96d2a5a192">

差了快 8 倍了

**Comment by zh-lx** [comment]
> @zh-lx 我加了这个插件，0.5 的版本，并且没有设置 forceInjectcache 这个参数，HMR 好慢呀
> 
> 这是加之前的 <img alt="image" width="365" src="https://private-user-images.githubusercontent.com/16385416/299586715-cb8f961b-5590-43f7-bccb-c23a0456bddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzA5MzcsIm5iZiI6MTcwNjE3MDYzNywicGF0aCI6Ii8xNjM4NTQxNi8yOTk1ODY3MTUtY2I4Zjk2MWItNTU5MC00M2Y3LWJjY2ItYzIzYTA0NTZiZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDdlOTJkZmRjNzFmYTkyMjEyNjhkNDMwMWRlNGVmODEzZjM3ZjRkZmI5NWVmY2JkYmU4ODM4YWVmNmNjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8lhbxjUCDSMgNQSk3JfFWQUwjNyAWu9ZGPMqar63kQ">
> 
> 这是加之后的 <img alt="企业微信截图_0dfd520a-3266-4fe9-a2c7-e2e92cc47cf2" width="362" src="https://private-user-images.githubusercontent.com/16385416/299586802-76a8c65e-7edc-41e9-80a9-6f96d2a5a192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzA5MzcsIm5iZiI6MTcwNjE3MDYzNywicGF0aCI6Ii8xNjM4NTQxNi8yOTk1ODY4MDItNzZhOGM2NWUtN2VkYy00MWU5LTgwYTktNmY5NmQyYTVhMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDkzNjgwZDc5OWYxNTllZTdlM2VmMDFjMGFlNzYwZDU1ZjE5YWJjODUwMTJjMGFmM2RkNzZhZmIyMjZmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buLpBU0CNyUVYj_NdDIt6v9oT8MPEOfsudivIHodTfo">
> 
> 差了快 9 倍了，本地开发很不方便

要提高编译速度需要显示设置 `forceInjectcache` 为 `true`；不过需要手动确认下设置为 `true` 时，你项目启动服务、关闭服务、再次启动后插件功能能否正常使用，能的话就设置 `forceInjectcache` 为 `true` 就好

**Comment by jo0ger** [comment]
> > @zh-lx 我加了这个插件，0.5 的版本，并且没有设置 forceInjectcache 这个参数，HMR 好慢呀
> > 这是加之前的 <img alt="image" width="365" src="https://private-user-images.githubusercontent.com/16385416/299586715-cb8f961b-5590-43f7-bccb-c23a0456bddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzA5MzcsIm5iZiI6MTcwNjE3MDYzNywicGF0aCI6Ii8xNjM4NTQxNi8yOTk1ODY3MTUtY2I4Zjk2MWItNTU5MC00M2Y3LWJjY2ItYzIzYTA0NTZiZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDdlOTJkZmRjNzFmYTkyMjEyNjhkNDMwMWRlNGVmODEzZjM3ZjRkZmI5NWVmY2JkYmU4ODM4YWVmNmNjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8lhbxjUCDSMgNQSk3JfFWQUwjNyAWu9ZGPMqar63kQ">
> > 这是加之后的 <img alt="企业微信截图_0dfd520a-3266-4fe9-a2c7-e2e92cc47cf2" width="362" src="https://private-user-images.githubusercontent.com/16385416/299586802-76a8c65e-7edc-41e9-80a9-6f96d2a5a192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzA5MzcsIm5iZiI6MTcwNjE3MDYzNywicGF0aCI6Ii8xNjM4NTQxNi8yOTk1ODY4MDItNzZhOGM2NWUtN2VkYy00MWU5LTgwYTktNmY5NmQyYTVhMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDkzNjgwZDc5OWYxNTllZTdlM2VmMDFjMGFlNzYwZDU1ZjE5YWJjODUwMTJjMGFmM2RkNzZhZmIyMjZmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buLpBU0CNyUVYj_NdDIt6v9oT8MPEOfsudivIHodTfo">
> > 差了快 9 倍了，本地开发很不方便
> 
> 要提高编译速度需要显式设置 `forceInjectcache` 为 `true`；不过需要手动确认下设置为 `true` 时，你项目启动服务、关闭服务、再次启动后插件功能能否正常使用，能的话就设置 `forceInjectcache` 为 `true` 就好

你指的启动服务关闭服务，指的是 本地的 dev server ？

**Comment by zh-lx** [comment]
> > > @zh-lx 我加了这个插件，0.5 的版本，并且没有设置 forceInjectcache 这个参数，HMR 好慢呀
> > > 这是加之前的 <img alt="image" width="365" src="https://private-user-images.githubusercontent.com/16385416/299586715-cb8f961b-5590-43f7-bccb-c23a0456bddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzA5MzcsIm5iZiI6MTcwNjE3MDYzNywicGF0aCI6Ii8xNjM4NTQxNi8yOTk1ODY3MTUtY2I4Zjk2MWItNTU5MC00M2Y3LWJjY2ItYzIzYTA0NTZiZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDdlOTJkZmRjNzFmYTkyMjEyNjhkNDMwMWRlNGVmODEzZjM3ZjRkZmI5NWVmY2JkYmU4ODM4YWVmNmNjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8lhbxjUCDSMgNQSk3JfFWQUwjNyAWu9ZGPMqar63kQ">
> > > 这是加之后的 <img alt="企业微信截图_0dfd520a-3266-4fe9-a2c7-e2e92cc47cf2" width="362" src="https://private-user-images.githubusercontent.com/16385416/299586802-76a8c65e-7edc-41e9-80a9-6f96d2a5a192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzA5MzcsIm5iZiI6MTcwNjE3MDYzNywicGF0aCI6Ii8xNjM4NTQxNi8yOTk1ODY4MDItNzZhOGM2NWUtN2VkYy00MWU5LTgwYTktNmY5NmQyYTVhMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDkzNjgwZDc5OWYxNTllZTdlM2VmMDFjMGFlNzYwZDU1ZjE5YWJjODUwMTJjMGFmM2RkNzZhZmIyMjZmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buLpBU0CNyUVYj_NdDIt6v9oT8MPEOfsudivIHodTfo">
> > > 差了快 9 倍了，本地开发很不方便
> > 
> > 
> > 要提高编译速度需要显式设置 `forceInjectcache` 为 `true`；不过需要手动确认下设置为 `true` 时，你项目启动服务、关闭服务、再次启动后插件功能能否正常使用，能的话就设置 `forceInjectcache` 为 `true` 就好
> 
> 你指的启动服务关闭服务，指的是 本地的 项目的 dev server 的重启？

是的

**Comment by jo0ger** [comment]
@zh-lx 那我先设置 true 吧，如果有问题，再反馈给你

**Comment by zh-lx** [comment]
> @zh-lx 那我先设置 true 吧，如果有问题，再反馈给你

好的

**Comment by zh-lx** [comment]
@jo0ger 刚刚升级了 `0.5.1` 版本进行了优化，彻底升级了这部分缓存策略，不需要再手动配置，也解决了部分项目冷启动 node server 无法开启的问题。可以升级到 `0.5.1` 版本体验一下

**Comment by jo0ger** [comment]
> @jo0ger 刚刚升级了 `0.5.1` 版本进行了优化，彻底升级了这部分缓存策略，不需要再手动配置，也解决了部分项目冷启动 node server 无法开启的问题。可以升级到 `0.5.1` 版本体验一下

cacheIdentifiers 这个配置哪提供的？

**Comment by zh-lx** [comment]
> > @jo0ger 刚刚升级了 `0.5.1` 版本进行了优化，彻底升级了这部分缓存策略，不需要再手动配置，也解决了部分项目冷启动 node server 无法开启的问题。可以升级到 `0.5.1` 版本体验一下
> 
> cacheIdentifiers 这个配置哪提供的？

`cacheIdentifiers` 不是 webpack 内置的属性，是我自己定义的一个参数，这样保证每次冷启动时这个参数是不同的能执行 `inject-loader` 启动 `node server` 服务。然后 HMR 就全部走 `cacheable: true` 的全缓存策略

**Comment by jo0ger** [comment]
我记得 babel-loader 也有这个参数
