### ISSUE TITLE
支持 vscode 内置浏览器（Simple Browser），直接打开对应代码文件

### ISSUE THREAD

**Issue by IMEVEN** [zh-lx/code-inspector#84]
支持 vscode 内置浏览器，直接打开对应代码文件，体验应该会更佳。

现在通过外部再调起 vscode，会闪一下。

另外，打开代码时替换了浏览器的窗口，打断了开发、浏览，如果检测有其他窗口时，能在非浏览器/当前窗口打开，体验就更丝滑了！

**Comment by zh-lx** [comment]
目前是支持在 vscode 内置的 Simple Browser 中使用的，vscode 打开文件的策略是优先在当前聚焦的 split 窗口打开，当你点击 Simple Browser 的页面时，会把 Simple Browser 所在的窗口聚焦，所以会优先在这个窗口打开。这属于 vscode 的策略，无法在插件内优化
