### ISSUE TITLE
接入后 code-inspector，操作终端报错

### ISSUE THREAD

**Issue by shangwfa** [zh-lx/code-inspector#87]
具体报错内容为：<img width="1061" alt="image" src="https://github.com/zh-lx/code-inspector/assets/7278589/09291176-d70d-4591-b8a5-53244ea3492f">

原因是：本地启动时设置了NODE_OPTIONS: "--openssl-legacy-provider" 导致的，移除是可以的，但是我这边依赖这个NODE_OPTIONS，会导致项目的其他错误，是否可以加个配置项，你这边启动进程时不要继承父进程的这个NODE_OPTIONS

我看了下代码大概在这个地方：
<img width="1464" alt="image" src="https://github.com/zh-lx/code-inspector/assets/7278589/094b6e65-5f90-4f8a-a024-d14b1fea85ef">

感谢感谢！！！

**Comment by zh-lx** [comment]
收到，我看看周末修复一下

**Comment by zh-lx** [comment]
已在 `0.5.2` 版本中修复该问题，欢迎安装体验
