### ISSUE TITLE
支持 Astro 框架

### ISSUE THREAD

**Issue by bowencool** [zh-lx/code-inspector#88]
<img width="1360" alt="image" src="https://github.com/zh-lx/code-inspector/assets/20217146/f8eb5305-b81c-4348-9c2b-30c430153448">

我发现Astro已经在网页上添加源码位置信息了，但找了半天不知道如何使用

**Comment by zh-lx** [comment]
目前还不支持，上面的源码是 astro 编译器自带的，不是插件注入的，astro 应该自带这个功能，可以查文档看下。插件会在后面支持 astro

**Comment by zh-lx** [comment]
已在 `0.9.0` 中支持了 astro 框架，欢迎安装体验

**Comment by bowencool** [comment]
> 已在 `0.9.0` 中支持了 astro 框架，欢迎安装体验

好像不能跳转到 md 文件，举个例子：文章详情页只能跳转到 PostDetail.astro 文件，而不能跳转到具体的内容文件 src/content/blog/xxx.md

插件很好用，加油！
