### ISSUE TITLE
编译tsx语法会触发eslint报错

### ISSUE THREAD

**Issue by wuchao05** [zh-lx/code-inspector#96]
<img width="1103" alt="image" src="https://github.com/zh-lx/code-inspector/assets/97175999/82427903-3acd-46a2-ae68-8b35e050f39b">

**Comment by zh-lx** [comment]
参考: https://inspector.fe-dev.cn/guide/api.html#enforcepre 插件设置 `enforcePre: 'false'` 试试，让插件中 loader 的执行顺序在 `eslint-loader` 的执行顺序之后
